---
extends:
  - react-app
  - eslint:recommended

globals:
  __DEV__: true
  # Promise: true

rules:
  quotes: ["error", "single"]
  strict: ["error", "never"]
  no-console: "warn"
  react-hooks/rules-of-hooks: error
